#! /bin/tcsh

set bin = /home/varrick/smart.exp/src/bin
set current = /home/varrick/smart.exp/src/test_lisa
set database = $current/indexed

# Very small test suite for smart on the included adi collection
# Run using "csh".  You can figure out more of what is going on by
# running this, and afterwords running
#        cd test
#        smart top.inter spec.atc spec_list "spec.nnn spec.atc"
# and playing around with the commands (try "help", "adv", "exp" first
# to get full list of available commands)

#########################################################################
# Make the lisa test collection
#########################################################################
# ./make_lisa
# echo "collection made"

/bin/rm -rf test
mkdir test
cd test


#########################################################################
# Perform two retrieval runs with the vectors already prepared by make_lisa
#########################################################################
cat > spec.nnn << EOF
include_file $database/spec
tr_file ./tr.nnn # Retrieve n document
rr_file ./rr.nnn # Retrieve all relevant document
run_name "Doc weight == Query weight == nnn"
EOF

$bin/smart retrieve spec.nnn
echo "retrieval run nnn.nnn done"

#########################################################################
# Additional Retrieval
#########################################################################

